### ISSUE TITLE
MVP spec

### ISSUE THREAD

**Issue by yugan2005** [awesomememo/frontend-js#1]
Brainstorm Ideas
Choose spec to be implemented for MVP

**Comment by yugan2005** [comment]
@ganneo pick the features that need be implemented in mvp

**Comment by ganneo** [comment]
# Task for MVP

- [x] Base web view
- [x] User
- [x] English Words
- [x] Add a card for a word
- [x] View card
- [x] Mark card correct or wrong
- [x] Associate word with time
- [x] Generate word list
- [x] Sound / img
- [x] Mark completion of a day

**Comment by yugan2005** [comment]
# Overall Tasks

* log in / sign up
* user account
* base web view
* Form for adding new item
* page for viewing an item
* associate item with time, generating the memorizing list by calculate the time
* sound / image associated with the item
* visual effects for going through memorizing items
* mark the right/wrong for the test  (either automatic or manual)
* mark day's completion
* Supported categories
    - English word
    - Chinese word
    - Bible verses
    - Math problems
* ranking among users
    - continuous days
    - quantity
    - correctness
* stimulus
    - badges
    - privileges
    - challenges
    - cashs
    - penalty skipping days
    - penalty too many mistakes
* forum

**Comment by yugan2005** [comment]
MVP version is released
